// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Identifies a node by exactly one of node_id, user_id, or email
 */
export type NodeResolver = {
  node_id?: string;
  user_id?: number;
  email?: string;
};

export type GetFooData = {
  body?: never;
  path?: never;
  query?: {
    search?: string;
    /**
     * Identifies a node by exactly one of its identifiers
     */
    node?: NodeResolver;
    ids?: Array<number>;
    cursor?: string;
  };
  url: '/foo';
};

export type GetFooResponses = {
  /**
   * OK
   */
  default: unknown;
};
